name: orchy-core CI

on:
  push:
    branches: [ main ]
    tags: '*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: latest
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - name: Trigger e2e
        if: ${{ matrix.node-version == '18.x' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TRIGGER_DEPLOY_ACCESS_TOKEN }}
          repository: orchy-mfe/orchy-examples
          event-type: trigger-pipeline